apiVersion: apps/v1
kind: Deployment
metadata:
  name: isaid-api
spec:
  selector:
    matchLabels:
      app: isaid-api
  replicas: 2
  template:
    metadata:
      labels:
        app: isaid-api
    spec:
      containers:
        - name: isaid
          image: 672604338600.dkr.ecr.us-east-1.amazonaws.com/isaid:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1